### ISSUE TITLE
Update by accelerometer wise default?

### ISSUE THREAD

**Issue by AeliusSaionji** [thuryn/your-local-weather#36]
I have no concrete proof, but I suspect that the update by accelerometer method is a huge battery drain.

Strangely, Android doesn't seem to record any useful data in the battery section of settings, but I have observed a rapid decrease in battery life when Your Local Weather updated to use accel by default.

Switch back to my preferred setting, "update every hour", and my battery life improves greatly. 

Maybe accel update shouldn't be the default?

**Comment by thuryn** [comment]
Accelerometer should be definitely more efficient. I havn't seen this problem on my phone, but I've made some optimization in the version 3.0.9 - the reads from database. Could you, please, try this version?

**Comment by AeliusSaionji** [comment]
Hmm, now it's just generally failing to find my location, but I think the battery issue is either solved or never was.

I'm using system location, not Mozilla. I'm not exactly certain what the differences between the two, is mozilla's just an Open Source implementation of location services? If the rest of the services on my phone are already using system location, would it be wiser to just use system location, because presumably is system will have cashed my location if other apps accessed it recently?

**Comment by AeliusSaionji** [comment]
Since I turned on debugging it has been updating location properly ¯\_(ツ)_/¯

**Comment by AeliusSaionji** [comment]
I still have some doubts about this. I've been trying to record data over the past week. No solid evidence, but I think I have a consistent pattern pointing to ylw's accel update.

I took three screenshots of battery usage with ylw's accel based update enabled. My battery life has been drastically reduced from normal. "Android System" eats up over 20%.

https://imgur.com/a/whDIF

I've taken two screenshots using hourly updates for ylw. The first result was not perfect, but still lower usage from Android System by a significant margin.
The second screenshot demonstrates the battery life I am used to: the phone lasted over 24 hours easily, and Android System is very low.

https://imgur.com/a/hZrBV

**Comment by thuryn** [comment]
I'll try to look on this issue. It could depend on hardware/OS - for example when the CPU is waken up etc. What HW/OS do you use?

**Comment by AeliusSaionji** [comment]
Pixel 2 XL
Android 8.1.0

**Comment by thuryn** [comment]
try the 3.0.17 version, please

**Comment by AeliusSaionji** [comment]
Results are mixed. Some days it's fine, some days I think it might be the cause of some drain, but overall it has improved a lot and it never drains as significantly as before.

**Comment by Lee-Carre** [comment]
@thuryn

> I would like to use Mozilla and Nominatim for all services in my phone, but it's not so easy.

Install Unified NLP (?) It can become the system's location supplier.
Mozilla Location Services & OSM Nominatim are 2 of the possible modules which may be used.

All of those are available via F-Droid (though you may need to add the IzzyOnDroid repository source for some of them; see F-Droid's documentation).

Although I disagree with AeliusSaionji's remark that these are merely libre-software implementations of system services, and share your perspective on respecting-the-user & user-freedom, AeliusSaionji does have a point re systems (technical) design being almost like a caching proxy, instead of each app having to re-implement the (proverbial) wheel.

The solution is to have those system services be libre-software in the first place: problem avoided.
