### ISSUE TITLE
Explanation of settings and features

### ISSUE THREAD

**Issue by AeliusSaionji** [thuryn/your-local-weather#4]
Hello!

I'm not sure what several of the functions in this app do. I think it would be beneficial if you described what each option does somewhere, if only in there README.md on this GitHub page.

To start, why does this app need to "make and manage phone calls"?

What does the address cache do?

What do each of the widget "wake up strategies" do?

What do each of the `location and address source` options do? What is the significance of these options?

Thanks!

**Comment by juanjgit** [comment]
Yes, please. Why those permission requeriments? "make and manage phone calls" for a weather app? It's like a buggy clone of "Good Weather" but with suspicious permission requeriments.

**Comment by thuryn** [comment]
Hello Aelius,
  thank you for you interest. Your definitely right, I have to describe all the options. I'm going to do it in the near future.

  Just to be clear about permission "make and manage phone calls":  The app can guess you location by system or by Mozilla location services (MLS). MLS is default. Finding location by MLS (by network in general) needs information about GSM network and/or wifis around. Getting information about GSM needs phone call permission.

**Comment by ildar** [comment]
Ah! I see now!
If you don't mind I just wanted to share my opinion here.
Implementing own location "services" in the app isn't a good idea: not just
as it is other apps&system's task but also because in case system doesn't
do that you already have manual place search.
Also may I suggest that the YLW wouldn't request precise location, only
rough location? GPS isn't that important for a weather app :))

**Comment by thuryn** [comment]
Regarding location services in the weather app: I had the same opinion indeed. I've spent many hours implementing intent based UnifiedNLP (this is needed because there is no simple way how to install original UnifiedNLP app - you need rooted phone etc.). When I had the usable implementation I created PR. But this PR is still not merged. The second reason to abandon this approach is usability from the user point of view - installation of four apps is really inconvenient (weather app, UnifiedNLP, location source and address geocoder.
So I've completely changed my mind and created app without any dependencies. I can debug, modify and update the release whenever I need.

I'll add the option to omit update by GPS ;-)

**Comment by ildar** [comment]
Good! thank you. Testing now.
BTW Settings is the total mess: widget settings are in "General" and app
settings in "Widget". Need to rework.

**Comment by AeliusSaionji** [comment]
Thank you!
