### ISSUE TITLE
[Feature request] add more than 3 locations

### ISSUE THREAD

**Issue by SkyWheel** [thuryn/your-local-weather#43]
Hi,
Currently YLW allows to cycle through 3 preset locations.
Could you please consider to increase the amount of locations?
Thank you.

**Comment by thuryn** [comment]
The limitation for 3 locations is due to the number of allowed connections to the openweathermap.org. I have to thing of this request - when I buy commercial access to openweathermap I need to get money back from users. I definitely have to solve this problem as number of users increases and I want to allow more then 3 locations also.

**Comment by SkyWheel** [comment]
Hi @thuryn ,
Implemented feature request #40 will resolve the issue :)
i.e. Without custom API key left the limitation of 3 locations.
But with OWM API key remove the limitation, and let users manage their OWM API connections.

**Comment by thuryn** [comment]
Implemented in the 4.1.5 version (omitted to mention the ticket number in commit)
