### ISSUE TITLE
highlight highest and lowest

### ISSUE THREAD

**Issue by M1Aston** [thuryn/your-local-weather#76]
Please highlight the highest and lowest temperatures in the daily forecasts. Some weather websites do this. I think it looks nice and it's quicker if you're looking for the highest and lowest temperatures. ;-D

**Comment by iillyyaa2033** [comment]
Started on implementing this feature and faced a problem: the real temperature is not the same as displayed.

On the left screenshot you can see that only one `+23°C` is minimal. On the right screenshot you can see that multiple `+24°C` is min/max and some of them is minimal but other is not.

| Only on one | Multiple |
| ---- | ---- |
| ![image](https://user-images.githubusercontent.com/17745136/90143402-415a1400-dd86-11ea-951d-ad5fbb28f072.png) | ![image](https://user-images.githubusercontent.com/17745136/90143467-533bb700-dd86-11ea-97f7-00b5e1e9c32f.png) |

This happens because the "real" temperature is something like 24.023451234, not 24.0

What I should do here?

**Comment by iillyyaa2033** [comment]
One decimal point solves first problem. Still dunno what to do with second
| Only on one | Multiple |
| ---- | ---- |
| ![image](https://user-images.githubusercontent.com/17745136/90146541-d4e11400-dd89-11ea-80fa-fd61c69fa539.png) | ![image](https://user-images.githubusercontent.com/17745136/90146657-fb06b400-dd89-11ea-89e5-2a7bfb7526de.png) |

**Comment by iillyyaa2033** [comment]
I leave second 'as is' because both temperatures **is** minimal or maximal ones
